### ISSUE TITLE
Cronjob PHP Warning

### ISSUE THREAD

**Issue by der-phillip** [schmitzal/tinyimg#32]
Ich bekomme beim ausführen diese Fehlermeldung:

> Die Ausführung von Task "Extbase-CommandController-Task (extbase)" ist fehlgeschlagen mit folgender Meldung: PHP Warning: explode() expects parameter 2 to be string, object given in /html/typo3/typo3_src-8.7.19/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1302

**Comment by schmitzal** [comment]
Would you mind trying to get the stack trace to know at which point the error is thrown?

**Comment by schmitzal** [comment]
Access to the TYPO3 would help.
Are you in the TYPO3 Slack? You could write me there a DM with a temporary admin user.

**Comment by der-phillip** [comment]
> Are you in the TYPO3 Slack? You could write me there a DM with a temporary admin user.

Yes I have, message is out now.

**Comment by Chegaro** [comment]
Is there a solution by now? 
The proglem is, that you call  
`$folder = $this->resourceFactory->getFolderObjectFromCombinedIdentifier($file->getParentFolder()); `
in line 73 of /tinyimg/Classes/Command/CompressImagesCommandController.php.
The required argument is a string that looks like this 1:/user_upload/ but it gets a folder object that can't be exploded.

**Comment by schmitzal** [comment]
Hello Chegaro,

thanks a lot for your merge request. I'll have a look at it, as soon as possible.

**Comment by der-phillip** [comment]
`Warning: Uncaught TYPO3\CMS\Core\Error\Exception: PHP Warning: require_once(/html/typo3/typo3conf/ext/tinyimg/Classes/Service/../../vendor/autoload.php): failed to open stream: No such file or directory in /html/typo3/typo3conf/ext/tinyimg/Classes/Service/CompressImageService.php line 15 in /html/typo3/typo3_src-8.7.20/typo3/sysext/core/Classes/Error/ErrorHandler.php:107 Stack trace: #0 /html/typo3/typo3conf/ext/tinyimg/Classes/Service/CompressImageService.php(15): TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'require_once(/h...', '/html/typo3/typ...', 15, Array) #1 /html/typo3/typo3conf/ext/tinyimg/Classes/Service/CompressImageService.php(15): require_once() #2 /html/typo3/typo3_src-8.7.20/vendor/composer/ClassLoader.php(444): include('/html/typo3/typ...') #3 /html/typo3/typo3_src-8.7.20/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/www/p4150...') #4 /html/typo3/typo3_src-8.7.20/vendor/typo3/class-alias-loader/src/ClassAliasLoader.php(130): Composer\Autoload\ClassLoader->loadClass('S in /html/typo3/typo3_src-8.7.20/typo3/sysext/core/Classes/Error/ErrorHandler.php on line 107

Fatal error: main(): Failed opening required '/html/typo3/typo3conf/ext/tinyimg/Classes/Service/../../vendor/autoload.php' (include_path='.:') in /html/typo3/typo3conf/ext/tinyimg/Classes/Service/CompressImageService.php on line 15`

**Comment by schmitzal** [comment]
Was the close a missclick or is the problem solved?

So you are running a Composer based setup right?

**Comment by der-phillip** [comment]
The problem based on commit #33 
The mistake comes when I execute the cron extbase tinyimg compress.

**Comment by schmitzal** [comment]
Did you update via composer or just downloaded and replaced it on the server?

**Comment by schmitzal** [comment]
I have updated the develop branch. Running tinyimg on a composer based setup works now like a charm for me.
I'll test it with a non composer setup tomorrow and if positiv release the new version with it fixes and TYPO3 9.5 support.
